// <auto-generated />
using AudioStreaming.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AudioStreaming.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220212094417_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AudioStreaming.Models.Canzone", b =>
                {
                    b.Property<int>("SongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlbumName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownnloadNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUserUploader")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SongTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SongID");

                    b.ToTable("Canzoni");
                });

            modelBuilder.Entity("AudioStreaming.Models.Canzone_Playlist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaylistID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongID")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("PlaylistID");

                    b.HasIndex("SongID");

                    b.ToTable("Canzone_Playlist");
                });

            modelBuilder.Entity("AudioStreaming.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Private")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaylistID");

                    b.ToTable("Playlist");
                });

            modelBuilder.Entity("AudioStreaming.Models.Canzone_Playlist", b =>
                {
                    b.HasOne("AudioStreaming.Models.Playlist", "Playlist")
                        .WithMany("Canzones")
                        .HasForeignKey("PlaylistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioStreaming.Models.Canzone", "Canzone")
                        .WithMany("Playlists")
                        .HasForeignKey("SongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canzone");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("AudioStreaming.Models.Canzone", b =>
                {
                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("AudioStreaming.Models.Playlist", b =>
                {
                    b.Navigation("Canzones");
                });
#pragma warning restore 612, 618
        }
    }
}
