// <auto-generated />
using AudioStreaming.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AudioStreaming.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AudioStreaming.Models.Canzone", b =>
                {
                    b.Property<int>("SongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlbumName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownnloadNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUserUploader")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SongTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SongID");

                    b.ToTable("Canzoni");
                });

            modelBuilder.Entity("AudioStreaming.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Private")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaylistID");

                    b.ToTable("Playlist");
                });

            modelBuilder.Entity("CanzonePlaylist", b =>
                {
                    b.Property<int>("EleCanzoniSongID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElePlaylistPlaylistID")
                        .HasColumnType("INTEGER");

                    b.HasKey("EleCanzoniSongID", "ElePlaylistPlaylistID");

                    b.HasIndex("ElePlaylistPlaylistID");

                    b.ToTable("CanzonePlaylist");
                });

            modelBuilder.Entity("CanzonePlaylist", b =>
                {
                    b.HasOne("AudioStreaming.Models.Canzone", null)
                        .WithMany()
                        .HasForeignKey("EleCanzoniSongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioStreaming.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("ElePlaylistPlaylistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
