// <auto-generated />
using AudioStreaming.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AudioStreaming.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AudioStreaming.Models.Canzone", b =>
                {
                    b.Property<int>("SongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlbumName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownnloadNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUserUploader")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SongTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SongID");

                    b.ToTable("Canzoni");

                    b.HasData(
                        new
                        {
                            SongID = 1,
                            AlbumName = "Album1",
                            DownnloadNumber = 0,
                            Duration = 120,
                            IDUserUploader = 1,
                            SongTitle = "Canzone1"
                        });
                });

            modelBuilder.Entity("AudioStreaming.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Private")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaylistID");

                    b.ToTable("Playlist");

                    b.HasData(
                        new
                        {
                            PlaylistID = 1,
                            Name = "Playlist1",
                            Private = true,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("CanzonePlaylist", b =>
                {
                    b.Property<int>("CanzonesSongID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaylistsPlaylistID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CanzonesSongID", "PlaylistsPlaylistID");

                    b.HasIndex("PlaylistsPlaylistID");

                    b.ToTable("CanzonePlaylist");

                    b.HasData(
                        new
                        {
                            CanzonesSongID = 1,
                            PlaylistsPlaylistID = 1
                        });
                });

            modelBuilder.Entity("CanzonePlaylist", b =>
                {
                    b.HasOne("AudioStreaming.Models.Canzone", null)
                        .WithMany()
                        .HasForeignKey("CanzonesSongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioStreaming.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsPlaylistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
